#ifndef __LINUX_VMM_CONFIG_H__
#define __LINUX_VMM_CONFIG_H__

#define HOST_VMM_ADDR_END 		CONFIG_HOST_VMM_ADDR_END
#define HOST_VMM_ADDR_BEGIN 	(CONFIG_HOST_VMM_ADDR_END - CONFIG_HOST_VMM_SIZE)

#endif
